---
AWSTemplateFormatVersion: "2010-09-09"

Description:
     This is cloudformation template for miliseconds application.
Resources:
    ApplicationLoadBalancer:
      Type: AWS::ApplicationLoadBalancing::LoadBalancer 
      Properties:
        VpcId: vpc-46003a3c 
        Subnets: 
          - subnet-6128c607 
          - subnet-58ab5f79 
          - subnet-5e5f6260 
          - subnet-7bf14836 
          - subnet-5a51ba05
          - subnet-e72888e9
        SecurityGroup: 
          - !REf MySecurityGroup 
        Listeners: 
          - LoadBalancerPort: 80 
            InstancePort: 80 
            Protocol: HTTP 
        HealthCheck: 
          Target: HTTP:80/ 
          HealthyThreshold: 3 
          UnhealthyThreshold: 5 
          Interval: 90 
          Timeout: 5 
    MyAutoScalingGroup:
      Type: AWS::AutoScaling::AutoScalingGroup 
      Properties: 
        AvailabilityZones: 
          - !Ref |
            - subnet-6128c607
            - subnet-58ab5f79
            - subnet-5e5f6260
            - subnet-7bf14836
            - subnet-5a51ba05
            - subnet-e72888e9
        LaunchConfigurationName: LaunchTemplate 
        MinSize: 1 
        MaxSize: 3 
        DesireCapacity: 2 
        LoadBalancerNames:
          - !Ref ApplicationLoadBalancer  
    MySecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDEscription: Enables HTTP for Flask Web Server 
        GroupName: Flask-WS-SG 
        VpcId: vpc-46003a3c
        SecurityGroupIngress: 
            -  IpProtocol: tcp
               FromPort: 80
               ToPort: 80
               CidrIp: 0.0.0.0/0     
    MyInstance:
      Type: AWS::EC2::Instance 
      Properties:
        ImageId: ami-08f3d892de259504d 
        InstanceType: t2.micro 
        SecurityGroupIds: 
            - !Ref MySecurityGroup 
        Tags:
            - 
               Key: Name 
               Value: !Sub Web Server of ${AWS::StackName} Stack 
        UserData: 
            Fn::Base64: 
               !Sub | 
               #! /bin/bash 
               yum update -y 
               yum install python3 -y 
               pip3 install flask 
               wget -p https://raw.githubusercontent.com/ftmkrz/clarusway-aws-workshop/master/002-milliseconds-converter/templates/index.html 
               wget -p https://raw.githubusercontent.com/ftmkrz/clarusway-aws-workshop/master/002-milliseconds-converter/templates/result.html
               wget https://raw.githubusercontent.com/ftmkrz/clarusway-aws-workshop/master/002-milliseconds-converter/app.py
               python3 app.py

Outputs:
    WebsiteURL:
      Description: Miliseconds Converter Application Website URL
      Value: !GetAtt ApplicationLoadBalancer.PublicDnsName 