AWSTemplateFormatVersion: 2010-09-09
Description: |
  Cloudformation Template for Kittens Carousel Static Website.
  This template deploys Kitten Caruousel App on S3 through Cloudfront and Route53.
Parameters:
  DomainName: 
    Description: DNS name of existing Route 53 Hosted Zone  
    Type: AWS::Route53::HostedZoneId::Id
  KittensDomainName:
    Description: Sub domain name for project 
    Type: string 
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: Must be a valid Dns Zone name
  MyCertificate:
    Description: The AWS Certificate Manager (ACM) certificate identifier.
    Type: String 
    Default: 

Resources:
MyBucket:
  Type: "AWS::S3::Bucket"
  Properties:
    AccessControl: PublicRead 
    BucketName: kittens.fatmakiraz.me
    WebiteConfiguration:
      IndexDocument: index.html
MyBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref MyBucket #required
      PolicyDocument:
        Statement:
        - Sid: "PublicReadforMyBucket"
          Effect: "Allow"
          Principal: "*"
          Action: S3:GetObject
          Resource: !Join ['',['arn:aws:s3:::', !Ref MyBucket, '/*']] 
# MyCertificate:
#     Type: "AWS::CertificateManager::Certificate"
#     Properties:
#       CertificateTransparencyLoggingPreference: DISABLED
#       DomainName: !Ref KittensDomainName #required
#       DomainValidationOptions:
#         - DomainName: !Ref KittensDomainName 
#           HostedZoneId: !Ref DomainName
#       ValidationMethod: DNS 
MyRoute53:
  Type: "AWS::Route53::RecordSetGroup"
  Properties:
    HostedZoneId: !Ref DomainName
    RecordSets:
      - Name: !Ref DomainName 
        Type: A 
        AliasTarget:
        DNSName:
        HostedZoneId: Z2FDTNDATAQYW2 
MyCloudfront: 
  Type: "AWS::CloudFront::Distribution"
  Properties:
    DistributionConfig: #required
      Aliases:
        - !Ref KittensDomainName
      DefaultCacheBehavior: 
        TargetOriginId: originid
        ViewerProtocolPolicy: allow-all
        AllowedMethods:
          - GET 
          - Head 
        ForwardedValues:
          QueryString: true 
          Cookies: 
            Forward: none
      Origins:
        - DomainName: !Select [2, !Split ["/", !GetAtt KittensBucket.WebsiteURL]]
          Id: KittensOriginId
          CustomOriginConfig:
            OriginProtocolPolicy: http-only
          ViewerCertificate:
            AcmCertificateArn: !Ref MyCertficate
            SslSupportMethod: sni-only
          PriceClass: PriceClass-all
          DefaultRootObject: index.html
          httpVersion: http2
          Enable: true
Outputs: 
  BucketName: 
    Description: S3 Bucket URL fot Kittens Website
    Value: !GetAtt MyBucket.WebsiteURL
  CloudfrontEndpoint:
    Description: Endpoint for Kittens Cloudfront Distribution
    Value: !GetAtt MyCloudfront.DomainName
  FullDomain:
    Description: Full DomainName of Kittens Carousel Application
    Value: !Ref KittensDomainName
    
  
  


  
        
  


  

  
